# Generated by Django 4.1.6 on 2023-02-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_student_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rf_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
