# Generated by Django 4.1.6 on 2023-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rf_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
